### ISSUE TITLE
Optimize chunk size

### ISSUE THREAD

**Issue by pnxdxt** [chesspecker/backend#8]
Right now, if chunk0 is filled with grade 0 puzzles AND if chunk1 is filled with grade 1 puzzles, the next grade 0 puzzle would be pushed to the chunk2.

For spaced-repetition to be optimized a puzzle with grade 0 should never be pushed to chunk2 except if chunk 1 is filled with only grade 0 puzzles.

**Comment by Nicolas-Menettrier** [comment]
Can you put more information on that issue ? I would like to contribute but I don't know which part of the code is affected

**Comment by pnxdxt** [comment]
Hi! Thank you for wanting to contribute! 🎉

As I was explaining the issue I found a quick workaround that will do the trick. However if you are willing to help I think something useful would be rethinking the puzzle model to store more data in order to create a dashboard. We could for example calculate the estimated time remaining to complete a set, the average number of mistakes for each puzzle, etc.
